// Code generated by `go-sdk-gen`. DO NOT EDIT.

package codegen

import (
	"codegen/client"
	"codegen/shared"
)

type Client struct {
	c      *client.Client
	Shared *shared.SharedService
}

// NewClient creates new SumUp API client.
// The client is by default configured environment variables (`SUMUP_API_KEY`).
// To override the default configuration use [ClientOption]s.
func NewClient(opts ...client.ClientOption) *Client {
	client := client.New(opts...)

	c := &Client{c: client}
	c.Shared = shared.NewSharedService(client)

	return c
}
