// Code generated by `go-sdk-gen`. DO NOT EDIT.

package petstore

import (
	"github.com/sumup/go-sdk-gen/examples/petstore/client"
	"github.com/sumup/go-sdk-gen/examples/petstore/pets"
)

type Client struct {
	c    *client.Client
	Pets *pets.PetsService
}

// NewClient creates new SumUp API client.
// The client is by default configured environment variables (`SUMUP_API_KEY`).
// To override the default configuration use [ClientOption]s.
func NewClient(opts ...client.ClientOption) *Client {
	client := client.New(opts...)

	c := &Client{c: client}
	c.Pets = pets.NewPetsService(client)

	return c
}
