// Code generated by `go-sdk-gen`. DO NOT EDIT.

package enums

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

// AllEnumTypes is a schema definition.
type AllEnumTypes struct {
	IntegerEnum AllEnumTypesIntegerEnum `json:"integer_enum"`
	// Format: int64
	IntegerWithFormatEnum *AllEnumTypesIntegerWithFormatEnum `json:"integer_with_format_enum,omitempty"`
	NumberEnum            AllEnumTypesNumberEnum             `json:"number_enum"`
	NumberWithFormatEnum  *AllEnumTypesNumberWithFormatEnum  `json:"number_with_format_enum,omitempty"`
	StringEnum            AllEnumTypesStringEnum             `json:"string_enum"`
}

// AllEnumTypesIntegerEnum is a schema definition.
type AllEnumTypesIntegerEnum int

const (
	AllEnumTypesIntegerEnum1 AllEnumTypesIntegerEnum = 1
	AllEnumTypesIntegerEnum2 AllEnumTypesIntegerEnum = 2
	AllEnumTypesIntegerEnum3 AllEnumTypesIntegerEnum = 3
)

// AllEnumTypesIntegerWithFormatEnum is a schema definition.
// Format: int64
type AllEnumTypesIntegerWithFormatEnum int64

const (
	AllEnumTypesIntegerWithFormatEnum1E18 AllEnumTypesIntegerWithFormatEnum = 1000000000000000000
	AllEnumTypesIntegerWithFormatEnum2E18 AllEnumTypesIntegerWithFormatEnum = 2000000000000000000
)

// AllEnumTypesNumberEnum is a schema definition.
type AllEnumTypesNumberEnum float64

const (
	AllEnumTypesNumberEnum11 AllEnumTypesNumberEnum = 1.1
	AllEnumTypesNumberEnum22 AllEnumTypesNumberEnum = 2.2
	AllEnumTypesNumberEnum33 AllEnumTypesNumberEnum = 3.3
)

// AllEnumTypesNumberWithFormatEnum is a schema definition.
type AllEnumTypesNumberWithFormatEnum float64

const (
	AllEnumTypesNumberWithFormatEnum1618 AllEnumTypesNumberWithFormatEnum = 1.618
	AllEnumTypesNumberWithFormatEnum314  AllEnumTypesNumberWithFormatEnum = 3.14
)

// AllEnumTypesStringEnum is a schema definition.
type AllEnumTypesStringEnum string

const (
	AllEnumTypesStringEnumValue1 AllEnumTypesStringEnum = "value1"
	AllEnumTypesStringEnumValue2 AllEnumTypesStringEnum = "value2"
	AllEnumTypesStringEnumValue3 AllEnumTypesStringEnum = "value3"
)

type SharedService service

// GetAllEnumTypes: Get all enum types
func (s *SharedService) GetAllEnumTypes(ctx context.Context) (*AllEnumTypes, error) {
	path := fmt.Sprintf("/enums")

	req, err := s.client.NewRequest(ctx, http.MethodGet, path, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("error building request: %v", err)
	}

	resp, err := s.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %v", err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusOK:
		var v AllEnumTypes
		if err := json.NewDecoder(resp.Body).Decode(&v); err != nil {
			return nil, fmt.Errorf("decode response: %s", err.Error())
		}

		return &v, nil
	default:
		return nil, fmt.Errorf("unexpected response %d: %s", resp.StatusCode, http.StatusText(resp.StatusCode))
	}
}
